In [ ]:
# !pip install pandas
# !pip install numpy

Collecting nba_api
  Downloading nba_api-1.11.4-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: numpy>=2.1.0 in c:\users\divya\anaconda3\lib\site-packages (from nba_api) (2.2.5)
Requirement already satisfied: pandas>=2.2.0 in c:\users\divya\anaconda3\lib\site-packages (from nba_api) (2.2.3)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in c:\users\divya\anaconda3\lib\site-packages (from nba_api) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\divya\anaconda3\lib\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\divya\anaconda3\lib\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\divya\anaconda3\lib\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\divya\anaconda3\lib\site-packages (from requests<3.0.0,>=2.32.3->nba_api) (2026.4.22)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\divya\anaconda3\lib\site-packages (from pandas>=2.2.0->nba_api) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\divya\anaconda3\lib\site-packages (from pandas>=2.2.0->nba_api) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\divya\anaconda3\lib\site-packages (from pandas>=2.2.0->nba_api) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\divya\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->nba_api) (1.17.0)
Downloading nba_api-1.11.4-py3-none-any.whl (322 kB)
Installing collected packages: nba_api
Successfully installed nba_api-1.11.4

In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
from nba_api.stats.endpoints import leaguegamefinder
import os
from PIL import Image
from IPython.display import IFrame

In [30]:
dict = {"a":[11,12,13],"b":[45,56,78]}

In [31]:
df = pd.DataFrame(dict)
df

    a   b
0  11  45
1  12  56
2  13  78

In [32]:
df.head()

    a   b
0  11  45
1  12  56
2  13  78

In [33]:
df.mean()

a    12.000000
b    59.666667
dtype: float64

In [34]:
def one_dict(list_dict):
    keys = list_dict[0].keys()
    out_dict ={key:[] for key in keys}
    for dict_ in list_dict:
        for key, value in dict_.items():
            out_dict[key].append(value)
    return out_dict

In [39]:
url = 'https://www.ibm.com/'
r = requests.get(url)
r.status_code
print(r.request.headers)

{'User-Agent': 'python-requests/2.32.3', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Cookie': '_abck=19761B38BE543C6A495804429B7A1C72~-1~YAAQzvUwF6IipDGfAQAA51CjURCKwTPFVPbBP+4OYCm9cF3nD42xl+/ALaAFZIkUtIHfaeMSzqrfgaOjdxaKsz42EdVkVaeea8xj8Ozb2STDAfgswnzufOkLrHo/7iyPAdL09IUNrmSDrGVDm60HNYtM+/daocDJGUZLlNaj4stf0AgNgT9gkc99ruVrfU3SGajGFNoB5PFfUpyUb15HFtqOWgbwI44hDJ8NYp5kLxaYoYGzHJZ79dC0QzoGjSXxYfqEFsDRrobIombBvP4LQ5rnrkI2JPhfCkciZke45M6yN5XH1/1JTlgSVuFOWQss7LJ7RmM6XGvkYosOdMJfSqW6iNoCHXZB9i8vPwP4mgqYjZfpKHDmeLsSEbBYLM/EKMVSgTzkD49B46fH/MM19mWjku1aY4zI5Sb/lpSLrX8iJ61W0kZrSu5w3yihaWchny0=~-1~-1~-1~-1~-1; bm_sz=A254A0841FE65ED3A226862C0642EBA2~YAAQzvUwF6MipDGfAQAA51CjUQAM5v3cqnHccScdHmztcG7n4z/2pwdqOVHoJDQT0N5FiGykcnWYOzJsl1G+WPCXy6ffaMFZaiKUfmHw0hCmiL8aIE76iOYsEVjpXqDrEfygqGSNEI9Qagan8jbj+DScCOyPyB43plGNYh+AUJy3npIPK2uWqOGJUBIWs5tBBo/P6lbqybnewwpVLd2JDNSYe4oh8Izd6wBOLiO4gsxS8W58qs6xoCPjXIcnP4NjLgSd03x5aPDW6nlvbCBPLNLtShJufcqd5E9X7FXcTqX+gcOh0LEkpw/n9kFnooJety33G7evCjwF0EoP2HOtgVU1yZ/SIj9bCiRw4K4XSJbiiQelTPoysNwdHMCaNDrptIQ50w==~3360308~4277062'}

In [40]:
print(r.request.body)

None

In [41]:
headers = r.headers
print(headers)

{'Content-Security-Policy': 'upgrade-insecure-requests', 'x-frame-options': 'SAMEORIGIN', 'Last-Modified': 'Sat, 11 Jul 2026 14:12:43 GMT', 'ETag': '"30e7e-65656736062bd-gzip"', 'Accept-Ranges': 'bytes', 'Content-Type': 'text/html;charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'Cache-Control': 'max-age=600', 'Expires': 'Sat, 11 Jul 2026 14:54:45 GMT', 'X-Akamai-Transformed': '0 - 0 -', 'Content-Encoding': 'gzip', 'Date': 'Sat, 11 Jul 2026 14:44:45 GMT', 'Content-Length': '41322', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding', 'Strict-Transport-Security': 'max-age=31536000'}

In [42]:
headers['Date']

'Sat, 11 Jul 2026 14:44:45 GMT'

In [43]:
headers['Content-Type']

'text/html;charset=utf-8'

In [44]:
r.encoding

'utf-8'