In [ ]:
# !pip install pandas
# !pip install numpy

Requirement already satisfied: pandas in c:\users\divya\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\divya\anaconda3\lib\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\divya\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\divya\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\divya\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\divya\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in c:\users\divya\anaconda3\lib\site-packages (2.2.5)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
dict = {"a":[11,12,13],"b":[45,56,78]}

In [8]:
df = pd.DataFrame(dict)
df

    a   b
0  11  45
1  12  56
2  13  78

In [9]:
df.head()

    a   b
0  11  45
1  12  56
2  13  78

In [10]:
df.mean()

a    12.000000
b    59.666667
dtype: float64